version: '3'

services:
  python-flask-hot-reload:
    build: .
    # expose:
    #   - 80
    ports:
      - '5000:80'
    volumes:
      - ./src:/app
    restart: unless-stopped
#     environment:
#       VIRTUAL_HOST: python-flask-hot-reload.foresee.icu
#       LETSENCRYPT_HOST: python-flask-hot-reload.foresee.icu
#       LETSENCRYPT_EMAIL: 437808@gmail.com
#     depends_on:
#       - nginx-proxy
#       - nginx-proxy-gen
#       - nginx-proxy-le

# networks:
#   default:
#     external:
#       name: nginx-proxy