version: '3'

services:
  mongo:
    image: mongo:3.4
    expose:
      - 27017
    volumes:
      - ./mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    restart: unless-stopped

  pythonflask:
    build: .
    ports:
      - '5000:80'
    volumes:
      - ./src:/app
    depends_on:
      - mongo
    restart: unless-stopped