version: '3'

services:
  neo4j:
    image: neo4j:3.4
    expose:
      - 7474
      - 7687
    # optionnally expose http and bolt on the host:
    ports:
      - '7474:7474'
      - '7687:7687'
    volumes:
      - ./neo4j-data:/data
      - ./neo4j-logs:/logs
    environment:
      - NEO4J_AUTH=neo4j/pass
    restart: unless-stopped

  pythonflask:
    container_name: pythonflask
    build: .
    image: pythonflask:0.1
    ports:
      - '5000:80'
    volumes:
      - ./src:/app
    depends_on:
      - neo4j
    restart: unless-stopped