version: '3'

services:
  python-flask:
    build: .
    expose:
      - 80
    restart: unless-stopped
#     environment:
#       VIRTUAL_HOST: python-flask.foresee.icu
#       LETSENCRYPT_HOST: python-flask.foresee.icu
#       LETSENCRYPT_EMAIL: 437808@gmail.com
#     depends_on:
#       - nginx-proxy
#       - nginx-proxy-gen
#       - nginx-proxy-le

# networks:
#   default:
#     external:
#       name: nginx-proxy