version: '3'

services:
  static-html:
    container_name: static-html
    image: nginx:alpine
    expose:
      - 80
    environment:
      VIRTUAL_HOST: static-html.foresee.icu
      LETSENCRYPT_HOST: static-html.foresee.icu
      LETSENCRYPT_EMAIL: 437808@gmail.com
    depends_on:
      - nginx-proxy
      - nginx-proxy-gen
      - nginx-proxy-le
    volumes:
      - ./src:/usr/share/nginx/html
    restart: unless-stopped

networks:
  default:
    external:
      name: nginx-proxy