version: '3'

services:
  static-html:
    image: nginx:alpine
    expose:
      - 80
    volumes:
      - ./src:/usr/share/nginx/html
    restart: unless-stopped
#     environment:
#       VIRTUAL_HOST: static-html.foresee.icu
#       LETSENCRYPT_HOST: static-html.foresee.icu
#       LETSENCRYPT_EMAIL: 437808@gmail.com
#     depends_on:
#       - nginx-proxy
#       - nginx-proxy-gen
#       - nginx-proxy-le

# networks:
#   default:
#     external:
#       name: nginx-proxy