version: '3'

services:
  postgres:
    image: postgres:11
    expose:
       - 5432
    # ports:
    #   - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=db
    restart: unless-stopped

  pythonflask:
    container_name: pythonflask
    build: .
    image: pythonflask:0.1
    expose:
      - 80
    ports:
      - "8555:80"
    volumes:
      - ./src:/app
    depends_on:
      - postgres
    restart: unless-stopped